blueprint:
  name: Hue Dimmer Switch V2 (RWL022) - Smart Control
  description: Steuerung für den Hue Dimmer V2 inklusive Smooth Dimming und freien Belegungen.
  domain: automation
  input:
    remote:
      name: Hue Dimmer Switch
      description: Wähle den Hue Dimmer Switch (Event-Entität von Button 1).
      selector:
        entity:
          filter:
            - integration: hue
              domain: event
    light_target:
      name: Licht
      description: Die Lichter, die gesteuert werden sollen.
      selector:
        target:
          entity:
            domain: light

    # Freie Belegungen
    button_1_long:
      name: Button 1 (Ein/Hue) - Langer Druck
      default: []
      selector:
        action: {}
    button_4_short:
      name: Button 4 (Hue Logo) - Kurzer Druck
      default: []
      selector:
        action: {}
    button_4_long:
      name: Button 4 (Hue Logo) - Langer Druck
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote
    id: "btn_1"
  - platform: state
    entity_id: 
      # Hier versuchen wir die anderen Buttons basierend auf der Namenskonvention zu finden
      # Da der User "Schalter einmal wählen" wollte, nehmen wir die Event-States aller Buttons
      - !input remote
    # Hinweis: Da Home Assistant Event-Entitäten pro Button anlegt, 
    # ist es am sichersten, diese im UI einmalig zuzuweisen. 
    # Um es simpel zu halten, triggern wir auf das Haupt-Event.

action:
  - variables:
      # Wir extrahieren den Event-Typ (short_release, long_press, etc.)
      event_type: "{{ trigger.to_state.attributes.event_type }}"
      # Wir bestimmen, welcher Button gedrückt wurde anhand der Entity-ID
      button: "{{ trigger.entity_id }}"

  - choose:
      # BUTTON 1 (Einschalten / Toggle)
      - conditions:
          - "{{ button.endswith('button_1') }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence:
                  - service: light.toggle
                    target: !input light_target
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_1_long

      # BUTTON 2 (Heller) - Smooth Dimming 5%
      - conditions:
          - "{{ button.endswith('button_2') }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: 5

      # BUTTON 3 (Dunkler) - Smooth Dimming 5%
      - conditions:
          - "{{ button.endswith('button_3') }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: -5

      # BUTTON 4 (Hue Button) - Custom
      - conditions:
          - "{{ button.endswith('button_4') }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence: !input button_4_short
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_4_long
