blueprint:
  name: Hue RWL022 Toggle and Smooth Dimmer (Event-Based)
  description: |
    ### Philips Hue Dimmer Switch (RWL022) Controller
    This blueprint provides full control over the Hue Dimmer Switch v2 using the official Philips Hue integration. 
    It is specifically designed for the RWL022 model (with the 'hue' logo on the bottom button).

    **Compatibility:** Works with the newest Hue Integration (2024+) that uses Event Entities.

    **Functionality:**
    * **Button 1 (Top):** Short Press = Toggle | Long Press = Custom Action
    * **Button 2 (Brighten):** Short Press = +10% | Long Hold = Smooth Increase
    * **Button 3 (Dim):** Short Press = -10% | Long Hold = Smooth Decrease
    * **Button 4 (Bottom):** Short & Long Press = Custom Actions

  domain: automation
  input:
    button_1_entity:
      name: Button 1 Event Entity
      selector:
        entity:
          domain: event
    
    button_2_entity:
      name: Button 2 Event Entity
      selector:
        entity:
          domain: event
    
    button_3_entity:
      name: Button 3 Event Entity
      selector:
        entity:
          domain: event
    
    button_4_entity:
      name: Button 4 Event Entity
      selector:
        entity:
          domain: event

    target_light:
      name: Target Light(s)
      selector:
        target:
          entity:
            domain: light

    button_1_long:
      name: Button 1 (Power) - Long Press Action
      default: []
      selector:
        action:

    button_4_short:
      name: Button 4 (Hue Logo) - Short Press Action
      default: []
      selector:
        action:

    button_4_long:
      name: Button 4 (Hue Logo) - Long Press Action
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input button_1_entity
    to: "short_release"
    id: "1_s"

  - platform: state
    entity_id: !input button_1_entity
    to: "long_release"
    id: "1_l"

  - platform: state
    entity_id: !input button_2_entity
    to: "short_release"
    id: "2_s"

  - platform: state
    entity_id: !input button_2_entity
    to: "initial_press"
    id: "2_h"

  - platform: state
    entity_id: !input button_3_entity
    to: "short_release"
    id: "3_s"

  - platform: state
    entity_id: !input button_3_entity
    to: "initial_press"
    id: "3_h"

  - platform: state
    entity_id: !input button_4_entity
    to: "short_release"
    id: "4_s"

  - platform: state
    entity_id: !input button_4_entity
    to: "long_release"
    id: "4_l"

action:
  - choose:
      # BUTTON 1: Power Toggle - Short Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == '1_s' }}"
        sequence:
          - service: light.toggle
            target: !input target_light

      # BUTTON 1: Power - Long Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == '1_l' }}"
        sequence: !input button_1_long

      # BUTTON 2: Brighten - Short Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == '2_s' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            
              brightness_step_pct: 10

      # BUTTON 2: Brighten - Long Hold
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == '2_h' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  
                    brightness_step_pct: 10
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # BUTTON 3: Dim - Short Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == '3_s' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            
              brightness_step_pct: -10

      # BUTTON 3: Dim - Long Hold
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == '3_h' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  
                    brightness_step_pct: -10
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # BUTTON 4: Custom - Short Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == '4_s' }}"
        sequence: !input button_4_short

      # BUTTON 4: Custom - Long Press
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == '4_l' }}"
        sequence: !input button_4_long
