blueprint:
  name: Hue RWL022 Toggle and Smooth Dimmer
  description: Philips Hue Dimmer Switch v2 (RWL022) Controller with Event Entities
  domain: automation
  input:
    button_1_entity:
      name: Button 1 Event Entity
      selector:
        entity:
          domain: event
    button_2_entity:
      name: Button 2 Event Entity
      selector:
        entity:
          domain: event
    button_3_entity:
      name: Button 3 Event Entity
      selector:
        entity:
          domain: event
    button_4_entity:
      name: Button 4 Event Entity
      selector:
        entity:
          domain: event
    target_light:
      name: Target Light(s)
      selector:
        target:
          entity:
            domain: light
    button_1_long:
      name: Button 1 Long Press Action
      default: []
      selector:
        action:
    button_4_short:
      name: Button 4 Short Press Action
      default: []
      selector:
        action:
    button_4_long:
      name: Button 4 Long Press Action
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input button_1_entity
    to: short_release
    id: btn1_short
  - platform: state
    entity_id: !input button_1_entity
    to: long_release
    id: btn1_long
  - platform: state
    entity_id: !input button_2_entity
    to: short_release
    id: btn2_short
  - platform: state
    entity_id: !input button_2_entity
    to: initial_press
    id: btn2_long
  - platform: state
    entity_id: !input button_3_entity
    to: short_release
    id: btn3_short
  - platform: state
    entity_id: !input button_3_entity
    to: initial_press
    id: btn3_long
  - platform: state
    entity_id: !input button_4_entity
    to: short_release
    id: btn4_short
  - platform: state
    entity_id: !input button_4_entity
    to: long_release
    id: btn4_long

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn1_short' }}"
        sequence:
          - service: light.toggle
            target: !input target_light
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn1_long' }}"
        sequence: !input button_1_long
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn2_short' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            
              brightness_step_pct: 10
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn2_long' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  
                    brightness_step_pct: 10
                    transition: 0.5
                - delay:
                    milliseconds: 500
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn3_short' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            
              brightness_step_pct: -10
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn3_long' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  
                    brightness_step_pct: -10
                    transition: 0.5
                - delay:
                    milliseconds: 500
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn4_short' }}"
        sequence: !input button_4_short
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn4_long' }}"
        sequence: !input button_4_long
