blueprint:
  name: "Hue Dimmer V2 (RWL022) - Pro Smooth & Safe Control"
  description: >
    # 🎮 Ultimate Smooth Control for Hue Dimmer V2 (RWL022)
    
    This professional-grade blueprint offers high-performance dimming while 
    maintaining strict system safety to prevent CPU spikes and infinite loops. 
    It is specifically designed for the Philips Hue Dimmer Switch V2 (Model RWL022).

    ### 🔑 Key Features:
    * **Advanced Loop Logic:** Uses internal Home Assistant loops for Buttons 2 & 3. 
      This prevents Zigbee network congestion and provides a much smoother 
      experience than standard "repeat" signals.
    * **Safety First:** Includes a hard limit (max 20 steps) for every dimming cycle. 
      Even if a "release" signal is lost in the air, the dimming will stop 
      automatically after ~6-8 seconds to protect your system (e.g., Intel NUC).
    * **Restart Mode:** Every new button press instantly kills any running loops, 
      ensuring immediate response and no "runaway" automations.

    ### ⌨️ Button Mapping & Actions:
    1.  **Button 1 (Top/Power):**
        * *Short Release:* Toggles the selected light(s).
        * *Long Press:* Trigger any custom action (e.g., "All Off" script).
    2.  **Button 2 (Brighten):**
        * *Hold:* Smoothly increases brightness using the Smart-Loop logic.
    3.  **Button 3 (Dim):**
        * *Hold:* Smoothly decreases brightness using the Smart-Loop logic.
    4.  **Button 4 (Hue Logo):**
        * *Short Release:* Custom action (e.g., Cycle Scenes).
        * *Long Press:* Custom action.

    ### ⚙️ Tuning Parameters:
    * **Dimming Step Size:** Percentage change per loop iteration (e.g., 10%). 
      How much the brightness changes with every "step" of the loop.
    * **Transition Time (Smoothness):** Duration of the fade between steps. 
      Higher values = smoother, but "rubbery" feeling. 
      Lower values = more direct and responsive, but potentially "choppy" on some bulbs.

    ### ⚠️ Installation Note:
    Select the four individual **Event entities** for your switch (button_1 through button_4). 
    Ensure you select the **Light** or **Light Group** you wish to control.

  domain: automation
  input:
    button_1:
      name: Button 1 Entity (Top)
      description: The event entity for the first button (e.g., event.xxx_button_1).
      selector: { entity: { filter: { domain: event } } }
    button_2:
      name: Button 2 Entity (Brighten)
      description: The event entity for the second button.
      selector: { entity: { filter: { domain: event } } }
    button_3:
      name: Button 3 Entity (Dim)
      description: The event entity for the third button.
      selector: { entity: { filter: { domain: event } } }
    button_4:
      name: Button 4 Entity (Hue Logo)
      description: The event entity for the fourth button.
      selector: { entity: { filter: { domain: event } } }
    light_target:
      name: Light Target
      description: The lights or groups to control.
      selector: { target: { entity: { domain: light } } }

    # --- TUNING PARAMETERS ---
    dim_step:
      name: Dimming Step Size
      description: Percentage change per loop iteration (e.g., 10%).
      default: 10
      selector: { number: { min: 1, max: 25, unit_of_measurement: "%" } }
    dim_transition:
      name: Transition Time (Smoothness)
      description: "Time for the transition. Higher values = smoother; lower values = more direct/snappy."
      default: 0.4
      selector: { number: { min: 0.1, max: 1, step: 0.1, unit_of_measurement: "s" } }

    # --- CUSTOM ACTIONS ---
    button_1_long:
      name: Button 1 - Long Press
      description: Action to perform when Button 1 is held.
      default: []
      selector: { action: {} }
    button_4_short:
      name: Button 4 - Short Press
      description: Action to perform on a quick press of the Hue logo.
      default: []
      selector: { action: {} }
    button_4_long:
      name: Button 4 - Long Press
      description: Action to perform when the Hue logo is held.
      default: []
      selector: { action: {} }

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: 
      - !input button_1
      - !input button_2
      - !input button_3
      - !input button_4

action:
  - variables:
      b1: !input button_1
      b2: !input button_2
      b3: !input button_3
      b4: !input button_4
      step: !input dim_step
      trans: !input dim_transition
      trigger_entity: "{{ trigger.entity_id }}"
      event_type: "{{ trigger.to_state.attributes.event_type }}"

  - choose:
      # --- BUTTON 1: TOGGLE / CUSTOM LONG ---
      - conditions: "{{ trigger_entity == b1 }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence:
                  - service: light.toggle
                    target: !input light_target
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_1_long

      # --- BUTTON 2: SMOOTH BRIGHTEN LOOP ---
      - conditions:
          - "{{ trigger_entity == b2 }}"
          - "{{ event_type == 'initial_press' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 20 and wait.trigger == none }}"
              sequence:
                - service: light.turn_on
                  target: !input light_target
                  data:
                    brightness_step_pct: "{{ step }}"
                    transition: "{{ trans }}"
                - wait_for_trigger:
                    - platform: state
                      entity_id: !input button_2
                      attribute: event_type
                      to: ["long_release", "short_release"]
                  timeout: "{{ trans }}"

      # --- BUTTON 3: SMOOTH DIM LOOP ---
      - conditions:
          - "{{ trigger_entity == b3 }}"
          - "{{ event_type == 'initial_press' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 20 and wait.trigger == none }}"
              sequence:
                - service: light.turn_on
                  target: !input light_target
                  data:
                    brightness_step_pct: "{{ step * -1 }}"
                    transition: "{{ trans }}"
                - wait_for_trigger:
                    - platform: state
                      entity_id: !input button_3
                      attribute: event_type
                      to: ["long_release", "short_release"]
                  timeout: "{{ trans }}"

      # --- BUTTON 4: CUSTOM ACTIONS ---
      - conditions: "{{ trigger_entity == b4 }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence: !input button_4_short
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_4_long
