blueprint:
  name: "Hue Dimmer V2 (RWL022) - Pro Smooth & Safe"
  description: >
    # 🎮 Ultimate Smooth Control for Hue Dimmer V2 (RWL022)
    
    This professional-grade blueprint offers high-performance dimming while 
    maintaining strict system safety to prevent CPU spikes and infinite loops.
    
    ### 🔧 Features:
    * **Advanced Loop Logic:** Uses internal Home Assistant loops for dimming.
    * **Tuning Parameters:** Adjust step size and transition speed via the UI.
    * **Safety Guardrails:** Automatic loop termination after 20 steps and `restart` mode protection.
    * **Custom Actions:** Fully assignable actions for Button 1 (Long) and Button 4 (Short/Long).
    
    ### ⌨️ Button Layout:
    1. **Button 1 (Top):** Short: Toggle | Long: Custom Action.
    2. **Button 2 (Sun):** Hold: Smooth Brighten (Customizable Speed).
    3. **Button 3 (Sun):** Hold: Smooth Dim (Customizable Speed).
    4. **Button 4 (Hue):** Short: Custom Action | Long: Custom Action.

  domain: automation
  input:
    button_1:
      name: Button 1 Entity
      description: Select the event entity for the top button.
      selector: { entity: { filter: { domain: event } } }
    button_2:
      name: Button 2 Entity
      description: Select the event entity for the brighten button.
      selector: { entity: { filter: { domain: event } } }
    button_3:
      name: Button 3 Entity
      description: Select the event entity for the dim button.
      selector: { entity: { filter: { domain: event } } }
    button_4:
      name: Button 4 Entity
      description: Select the event entity for the bottom logo button.
      selector: { entity: { filter: { domain: event } } }
    light_target:
      name: Light Target
      description: The lights or groups to control.
      selector: { target: { entity: { domain: light } } }

    # --- TUNING PARAMETERS ---
    dim_step:
      name: Dimming Step Size
      description: Percentage change per loop iteration (e.g., 10%).
      default: 10
      selector: { number: { min: 1, max: 25, unit_of_measurement: "%" } }
    dim_transition:
      name: Transition Time (Smoothness)
      description: "Duration of the fade between steps. Higher = Smoother; Lower = More responsive."
      default: 0.4
      selector: { number: { min: 0.1, max: 1, step: 0.1, unit_of_measurement: "s" } }

    # --- CUSTOM ACTIONS ---
    button_1_long:
      name: Button 1 - Long Press
      default: []
      selector: { action: {} }
    button_4_short:
      name: Button 4 - Short Press
      default: []
      selector: { action: {} }
    button_4_long:
      name: Button 4 - Long Press
      default: []
      selector: { action: {} }

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: 
      - !input button_1
      - !input button_2
      - !input button_3
      - !input button_4

action:
  - variables:
      # Loading inputs into local variables
      b1: !input button_1
      b2: !input button_2
      b3: !input button_3
      b4: !input button_4
      step: !input dim_step
      trans: !input dim_transition
      # Event context
      trigger_entity: "{{ trigger.entity_id }}"
      event_type: "{{ trigger.to_state.attributes.event_type }}"

  - choose:
      # BUTTON 1: TOGGLE / CUSTOM LONG
      - conditions: "{{ trigger_entity == b1 }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence: [service: light.toggle, target: !input light_target]
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_1_long

      # BUTTON 2: SMOOTH BRIGHTEN LOOP
      - conditions:
          - "{{ trigger_entity == b2 }}"
          - "{{ event_type == 'initial_press' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 20 and wait.trigger == none }}"
              sequence:
                - service: light.turn_on
                  target: !input light_target
                  data:
                    brightness_step_pct: "{{ step }}"
                    transition: "{{ trans }}"
                - wait_for_trigger:
                    - platform: state
                      entity_id: !input button_2
                      attribute: event_type
                      to: ["long_release", "short_release"]
                  timeout: "{{ trans }}"

      # BUTTON 3: SMOOTH DIM LOOP
      - conditions:
          - "{{ trigger_entity == b3 }}"
          - "{{ event_type == 'initial_press' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ repeat.index < 20 and wait.trigger == none }}"
              sequence:
                - service: light.turn_on
                  target: !input light_target
                  data:
                    brightness_step_pct: "{{ step * -1 }}"
                    transition: "{{ trans }}"
                - wait_for_trigger:
                    - platform: state
                      entity_id: !input button_3
                      attribute: event_type
                      to: ["long_release", "short_release"]
                  timeout: "{{ trans }}"

      # BUTTON 4: CUSTOM ACTIONS
      - conditions: "{{ trigger_entity == b4 }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence: !input button_4_short
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_4_long
