blueprint:
  name: Hue RWL022 Toggle and Smooth Dimmer (Event-Based)
  description: |
    ### Philips Hue Dimmer Switch (RWL022) Controller
    This blueprint provides full control over the Hue Dimmer Switch v2 using the official Philips Hue integration. 
    It is specifically designed for the RWL022 model (with the 'hue' logo on the bottom button).

    **Compatibility:** Works with the newest Hue Integration (2024+) that uses Event Entities.

    **Functionality:**
    * **Button 1 (Top):** 
        * *Short Press:* Toggles the selected light(s).
        * *Long Press:* Customizable action.
    * **Button 2 (Brighten):** 
        * *Short Press:* Increases brightness by 10%.
        * *Long Press (Hold):* Continuously increases brightness smoothly until released.
    * **Button 3 (Dim):** 
        * *Short Press:* Decreases brightness by 10%.
        * *Long Press (Hold):* Continuously decreases brightness smoothly until released.
    * **Button 4 (Bottom):** 
        * *Short & Long Press:* Fully customizable actions (e.g., Scenes, Scripts).

  domain: automation
  input:
    button_1_entity:
      name: Button 1 Event Entity
      description: Select the "Button 1" event entity from your Hue Dimmer Switch
      selector:
        entity:
          domain: event
    
    button_2_entity:
      name: Button 2 Event Entity
      description: Select the "Button 2" (Brighten) event entity
      selector:
        entity:
          domain: event
    
    button_3_entity:
      name: Button 3 Event Entity
      description: Select the "Button 3" (Dim) event entity
      selector:
        entity:
          domain: event
    
    button_4_entity:
      name: Button 4 Event Entity
      description: Select the "Button 4" (Hue Logo) event entity
      selector:
        entity:
          domain: event

    target_light:
      name: Target Light(s)
      description: These lights are controlled by the Power Toggle (Button 1) and Dimming (Buttons 2 & 3).
      selector:
        target:
          entity:
            domain: light

    brightness_step:
      name: Brightness Step Percentage
      description: How much brightness changes per short press (1-50%)
      default: 10
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    dimming_interval:
      name: Smooth Dimming Interval
      description: Delay in seconds between brightness steps during long hold (0.1-1.0s)
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          unit_of_measurement: "s"

    button_1_long:
      name: Button 1 (Power) - Long Press Action
      default: []
      selector:
        action:

    button_4_short:
      name: Button 4 (Hue Logo) - Short Press Action
      default: []
      selector:
        action:

    button_4_long:
      name: Button 4 (Hue Logo) - Long Press Action
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input button_1_entity
    to: "short_release"
    id: "1_s"

  - platform: state
    entity_id: !input button_1_entity
    to: "long_release"
    id: "1_l"

  - platform: state
    entity_id: !input button_2_entity
    to: "short_release"
    id: "2_s"

  - platform: state
    entity_id: !input button_2_entity
    to: "initial_press"
    id: "2_h"

  - platform: state
    entity_id: !input button_3_entity
    to: "short_release"
    id: "3_s"

  - platform: state
    entity_id: !input button_3_entity
    to: "initial_press"
    id: "3_h"

  - platform: state
    entity_id: !input button_4_entity
    to: "short_release"
    id: "4_s"

  - platform: state
    entity_id: !input button_4_entity
    to: "long_release"
    id: "4_l"

action:
  - choose:
      # BUTTON 1: Power Toggle
      - conditions: "{{ trigger.id == '1_s' }}"
        sequence:
          - service: light.toggle
            target: !input target_light

      - conditions: "{{ trigger.id == '1_l' }}"
        sequence: !input button_1_long

      # BUTTON 2: Brightness Increase - Short Press
      - conditions: "{{ trigger.id == '2_s' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            
              brightness_step_pct: 10

      # BUTTON 2: Brightness Increase - Long Hold (Smooth)
      - conditions: "{{ trigger.id == '2_h' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  
                    brightness_step_pct: 10
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # BUTTON 3: Brightness Decrease - Short Press
      - conditions: "{{ trigger.id == '3_s' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            
              brightness_step_pct: -10

      # BUTTON 3: Brightness Decrease - Long Hold (Smooth)
      - conditions: "{{ trigger.id == '3_h' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  
                    brightness_step_pct: -10
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # BUTTON 4: Custom Actions
      - conditions: "{{ trigger.id == '4_s' }}"
        sequence: !input button_4_short

      - conditions: "{{ trigger.id == '4_l' }}"
        sequence: !input button_4_long
