blueprint:
  name: Native Hue - RWL022 Full Config (Smooth Dimming)
  description: |
    Control lights with a Philips Hue Dimmer Switch (RWL022) via NATIVE Hue integration.
    - Buttons 1 & 4: Support Short and Long Press.
    - Buttons 2 & 3: Support Short Press and Smooth Dimming (Hold).
  domain: automation
  input:
    device:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
          # Hides lamps by requiring a battery sensor
          entity:
            domain: sensor
            device_class: battery
    target_light:
      name: Light(s) for smooth dimming
      selector:
        target:
          entity:
            domain: light

    # ACTIONS
    button_1_short:
      name: "Button 1 (Power) - Short Press"
      default: []
      selector:
        action:
    button_1_long:
      name: "Button 1 (Power) - Long Press"
      default: []
      selector:
        action:
    button_2_short:
      name: "Button 2 (Brighten) - Short Press"
      default: []
      selector:
        action:
    button_3_short:
      name: "Button 3 (Dim) - Short Press"
      default: []
      selector:
        action:
    button_4_short:
      name: "Button 4 (Hue Logo) - Short Press"
      default: []
      selector:
        action:
    button_4_long:
      name: "Button 4 (Hue Logo) - Long Press"
      default: []
      selector:
        action:

mode: restart # Stopping dimming loops on any new button event
max_exceeded: silent

trigger:
  # SHORT RELEASES
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 1
    id: "1_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 2
    id: "2_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 3
    id: "3_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 4
    id: "4_short"

  # LONG RELEASES
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_long_release
    subtype: 1
    id: "1_long"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_long_release
    subtype: 4
    id: "4_long"

  # HOLD FOR DIMMING (Initial Press)
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    subtype: 2
    id: "2_hold"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    subtype: 3
    id: "3_hold"

action:
  - choose:
      # BUTTON 1
      - conditions: "{{ trigger.id == '1_short' }}"
        sequence: !input button_1_short
      - conditions: "{{ trigger.id == '1_long' }}"
        sequence: !input button_1_long

      # BUTTON 2 (Smooth Brighten)
      - conditions: "{{ trigger.id == '2_short' }}"
        sequence: !input button_2_short
      - conditions: "{{ trigger.id == '2_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay: 0.5

      # BUTTON 3 (Smooth Dim)
      - conditions: "{{ trigger.id == '3_short' }}"
        sequence: !input button_3_short
      - conditions: "{{ trigger.id == '3_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay: 0.5

      # BUTTON 4
      - conditions: "{{ trigger.id == '4_short' }}"
        sequence: !input button_4_short
      - conditions: "{{ trigger.id == '4_long' }}"
        sequence: !input button_4_long
