blueprint:
  name: Native Hue - Multi-Model Dimmer Switch (RWL020/021/022)
  description: |
    Steuerung für ALLE Philips Hue Dimmer Schalter über die NATIVE Hue Integration.
    Unterstützt RWL020 (US v1), RWL021 (EU v1) und RWL022 (v2 mit Hue-Button).
    
    Aktionen: Kurzer Druck und langes Halten (Release) für alle 4 Tasten.
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Schalter
      description: Wähle den Schalter aus (Egal ob v1 oder v2).
      selector:
        device:
          integration: hue
          # Wir lassen das Model weg, damit alle 3 Typen wählbar sind
          
    # TASTE 1 (Ganz oben: On / Power)
    btn_1_short:
      name: "Taste 1 - Kurz"
      default: []
      selector:
        action:
    btn_1_long:
      name: "Taste 1 - Lang (Halten)"
      default: []
      selector:
        action:

    # TASTE 2 (Oben Mitte: Heller)
    btn_2_short:
      name: "Taste 2 - Kurz"
      default: []
      selector:
        action:
    btn_2_long:
      name: "Taste 2 - Lang (Halten)"
      default: []
      selector:
        action:

    # TASTE 3 (Unten Mitte: Dunkler)
    btn_3_short:
      name: "Taste 3 - Kurz"
      default: []
      selector:
        action:
    btn_3_long:
      name: "Taste 3 - Lang (Halten)"
      default: []
      selector:
        action:

    # TASTE 4 (Ganz unten: Off / Hue Logo)
    btn_4_short:
      name: "Taste 4 - Kurz"
      default: []
      selector:
        action:
    btn_4_long:
      name: "Taste 4 - Lang (Halten)"
      default: []
      selector:
        action:

mode: parallel
max_exceeded: silent

trigger:
  - platform: device
    domain: hue
    device_id: !input remote
    type: remote_button_short_release
    id: "short"
  - platform: device
    domain: hue
    device_id: !input remote
    type: remote_button_long_release
    id: "long"

action:
  - variables:
      # Die Button-ID (subtype) wird vom Trigger geliefert (1, 2, 3 oder 4)
      button_id: "{{ trigger.subtype }}"
      press_type: "{{ trigger.id }}"

  - choose:
      # Taste 1
      - conditions: "{{ button_id == 1 and press_type == 'short' }}"
        sequence: !input btn_1_short
      - conditions: "{{ button_id == 1 and press_type == 'long' }}"
        sequence: !input btn_1_long

      # Taste 2
      - conditions: "{{ button_id == 2 and press_type == 'short' }}"
        sequence: !input btn_2_short
      - conditions: "{{ button_id == 2 and press_type == 'long' }}"
        sequence: !input btn_2_long

      # Taste 3
      - conditions: "{{ button_id == 3 and press_type == 'short' }}"
        sequence: !input btn_3_short
      - conditions: "{{ button_id == 3 and press_type == 'long' }}"
        sequence: !input btn_3_long

      # Taste 4
      - conditions: "{{ button_id == 4 and press_type == 'short' }}"
        sequence: !input btn_4_short
      - conditions: "{{ button_id == 4 and press_type == 'long' }}"
        sequence: !input btn_4_long
