blueprint:
  name: "Hue Dimmer V2 (RWL022) - Ein-Klick-Steuerung FIX"
  description: >
    Wähle einmal das Gerät (über den Batterie-Sensor-Filter) und das Licht. 
    Die Button-Entitäten werden automatisch über den Namen aufgelöst.
  domain: automation
  input:
    remote_device:
      name: Hue Dimmer Switch
      description: Wähle den Schalter aus.
      selector:
        device:
          integration: hue
          multiple: false
          entity:
            domain: sensor
            device_class: battery
    light_target:
      name: Licht / Gruppe
      selector:
        target:
          entity:
            domain: light
    button_1_long:
      name: Button 1 (Ein) - Langer Druck
      default: []
      selector: { action: {} }
    button_4_short:
      name: Button 4 (Hue Logo) - Kurzer Druck
      default: []
      selector: { action: {} }
    button_4_long:
      name: Button 4 (Hue Logo) - Langer Druck
      default: []
      selector: { action: {} }

mode: restart
max_exceeded: silent

trigger:
  # Wir triggern allgemein auf Events in HA. 
  # In der Action filtern wir dann, ob das Event zu unserem Gerät gehört.
  - platform: event
    event_type: state_changed

action:
  - variables:
      # FIX: Wir holen uns die Device-ID vom Input
      selected_device: !input remote_device
      # Wir finden die Button-1 Entität dieses Geräts, um den Basis-Namen zu haben
      # Das ist der sicherste Weg, um die "Ein-Klick-Logik" zu behalten
      button_1_entity: "{{ device_entities(selected_device) | select('search', 'button_1') | first }}"
      base_name: "{{ button_1_entity.replace('_button_1', '') }}"
      
      # Event-Daten extrahieren
      triggered_entity: "{{ trigger.event.data.entity_id }}"
      event_type: "{{ trigger.event.data.new_state.attributes.event_type if trigger.event.data.new_state is not none }}"

  # Wir prüfen zuerst, ob die triggernde Entität überhaupt zu unserem Schalter gehört
  - condition: template
    value_template: "{{ triggered_entity.startswith(base_name) }}"

  - choose:
      # Button 1: Toggle / Long Press
      - conditions: "{{ triggered_entity == base_name ~ '_button_1' }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence:
                  - service: light.toggle
                    target: !input light_target
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_1_long

      # Button 2: Heller (5%)
      - conditions:
          - "{{ triggered_entity == base_name ~ '_button_2' }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: 5

      # Button 3: Dunkler (5%)
      - conditions:
          - "{{ triggered_entity == base_name ~ '_button_3' }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: -5

      # Button 4: Custom
      - conditions: "{{ triggered_entity == base_name ~ '_button_4' }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence: !input button_4_short
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_4_long
