blueprint:
  name: Native Hue - RWL022 Final Fix (Toggle & Smooth Dim)
  description: |
    Control lights with a Philips Hue Dimmer Switch (RWL022) via NATIVE Hue integration.
    
    Fixed Logic:
    - Button 1 Short: Always toggles the Target Light(s).
    - Button 2/3: Smooth dimming for Target Light(s) (Hold to fade, Tap to step).
    
    Customizable:
    - Button 1 Long Press.
    - Button 4 Short & Long Press.
  domain: automation
  input:
    device:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
          entity:
            domain: sensor
            device_class: battery
    target_light:
      name: Target Light(s)
      description: These lights will be toggled by Button 1 and dimmed by Buttons 2 & 3.
      selector:
        target:
          entity:
            domain: light

    # Custom Action Slots
    button_1_long:
      name: "Button 1 (Power) - Long Press"
      default: []
      selector:
        action:
    button_4_short:
      name: "Button 4 (Hue Logo) - Short Press"
      default: []
      selector:
        action:
    button_4_long:
      name: "Button 4 (Hue Logo) - Long Press"
      default: []
      selector:
        action:

mode: restart # Stoppt Dimmen sofort beim Loslassen
max_exceeded: silent

trigger:
  # Button 1
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: button_1
    id: "1_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_long_release
    subtype: button_1
    id: "1_long"

  # Button 2
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: button_2
    id: "2_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    subtype: button_2
    id: "2_hold"

  # Button 3
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: button_3
    id: "3_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    subtype: button_3
    id: "3_hold"

  # Button 4
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: button_4
    id: "4_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_long_release
    subtype: button_4
    id: "4_long"

action:
  - choose:
      # TASTE 1: Festgelegter Toggle
      - conditions: "{{ trigger.id == '1_short' }}"
        sequence:
          - service: light.toggle
            target: !input target_light

      # TASTE 1: Frei wählbar (Long)
      - conditions: "{{ trigger.id == '1_long' }}"
        sequence: !input button_1_long

      # TASTE 2: Heller (Tap = 10%, Hold = Smooth Loop)
      - conditions: "{{ trigger.id == '2_short' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: 10
      - conditions: "{{ trigger.id == '2_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay: 0.5

      # TASTE 3: Dunkler (Tap = -10%, Hold = Smooth Loop)
      - conditions: "{{ trigger.id == '3_short' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: -10
      - conditions: "{{ trigger.id == '3_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay: 0.5

      # TASTE 4: Frei wählbar (Short)
      - conditions: "{{ trigger.id == '4_short' }}"
        sequence: !input button_4_short

      # TASTE 4: Frei wählbar (Long)
      - conditions: "{{ trigger.id == '4_long' }}"
        sequence: !input button_4_long
