blueprint:
  name: Native Hue - RWL022 Complete (Short, Long & Smooth)
  description: |
    Control anything with your Hue Dimmer (RWL022) via Native Hue.
    - Buttons 1-4: Configure Short and Long press.
    - Buttons 2-3: Hold to dim smoothly (this is the Long Press action).
  domain: automation
  input:
    device:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
          entity:
            domain: sensor
            device_class: battery
    target_light:
      name: Light(s) for smooth dimming (Buttons 2 & 3)
      selector:
        target:
          entity:
            domain: light

    # BUTTON 1
    button_1_short:
      name: "Button 1 (Power) - Short Press"
      default: []
      selector:
        action:
    button_1_long:
      name: "Button 1 (Power) - Long Press"
      default: []
      selector:
        action:

    # BUTTON 2 (Brighten)
    button_2_short:
      name: "Button 2 (Brighten) - Short Press"
      default: []
      selector:
        action:
    # No Long Press selector for 2 & 3 because "Hold" is used for smooth dimming logic

    # BUTTON 3 (Dim)
    button_3_short:
      name: "Button 3 (Dim) - Short Press"
      default: []
      selector:
        action:

    # BUTTON 4 (Hue Logo)
    button_4_short:
      name: "Button 4 (Hue Logo) - Short Press"
      default: []
      selector:
        action:
    button_4_long:
      name: "Button 4 (Hue Logo) - Long Press"
      default: []
      selector:
        action:

mode: restart # Essential for stopping dimming loops
max_exceeded: silent

trigger:
  # All Short Releases
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 1
    id: "1_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 2
    id: "2_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 3
    id: "3_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 4
    id: "4_short"

  # All Long Releases
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_long_release
    subtype: 1
    id: "1_long"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_long_release
    subtype: 4
    id: "4_long"

  # Initial Presses for Dimming Loops
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    subtype: 2
    id: "2_hold"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    subtype: 3
    id: "3_hold"

action:
  - choose:
      # BUTTON 1
      - conditions: "{{ trigger.id == '1_short' }}"
        sequence: !input button_1_short
      - conditions: "{{ trigger.id == '1_long' }}"
        sequence: !input button_1_long

      # BUTTON 2 (Brighten)
      - conditions: "{{ trigger.id == '2_short' }}"
        sequence: !input button_2_short
      - conditions: "{{ trigger.id == '2_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay: 0.5

      # BUTTON 3 (Dim)
      - conditions: "{{ trigger.id == '3_short' }}"
        sequence: !input button_3_short
      - conditions: "{{ trigger.id == '3_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay: 0.5

      # BUTTON 4
      - conditions: "{{ trigger.id == '4_short' }}"
        sequence: !input button_4_short
      - conditions: "{{ trigger.id == '4_long' }}"
        sequence: !input button_4_long
