blueprint:
  name: Hue RWL022 Toggle and Smooth Dimmer
  description: |
    ### Philips Hue Dimmer Switch (RWL022) Controller
    This blueprint provides full control over the Hue Dimmer Switch v2 using the official Philips Hue integration. 
    It is specifically designed for the RWL022 model (with the 'hue' logo on the bottom button).

    **Functionality:**
    * **Button 1 (Top):** * *Short Press:* Hardcoded to Toggle the selected 'Target Light(s)'.
        * *Long Press:* Customizable action.
    * **Button 2 (Brighten):** * *Short Press:* Increases brightness by 10%.
        * *Long Press (Hold):* Continuously increases brightness smoothly until released.
    * **Button 3 (Dim):** * *Short Press:* Decreases brightness by 10%.
        * *Long Press (Hold):* Continuously decreases brightness smoothly until released.
    * **Button 4 (Bottom):** * *Short & Long Press:* Fully customizable actions (e.g., Scenes, Scripts).

    **Technical Implementation:**
    * Uses the 'Battery-Filter' to ensure only remotes are selectable and all Hue lamps are hidden.
    * Uses `mode: restart` to instantly kill the dimming loop as soon as you release the button.
    * Uses native event-matching for the 'button_1' to 'button_4' subtypes.
  domain: automation
  input:
    device:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
          # This entity check removes all lamps (Bedroom 1-5) from the list
          entity:
            domain: sensor
            device_class: battery
    target_light:
      name: Target Light(s)
      description: These lights are controlled by the Power Toggle (Button 1) and Dimming (Buttons 2 & 3).
      selector:
        target:
          entity:
            domain: light

    # Customizable Action Slots
    button_1_long:
      name: Button 1 (Power) - Long Press Action
      default: []
      selector:
        action:
    button_4_short:
      name: Button 4 (Hue Logo) - Short Press Action
      default: []
      selector:
        action:
    button_4_long:
      name: Button 4 (Hue Logo) - Long Press Action
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  # Trigger mapping based on native hue event types
  - platform: device
    domain: hue
    device_id: !input device
    type: short_release
    subtype: button_1
    id: "1_s"
  - platform: device
    domain: hue
    device_id: !input device
    type: long_release
    subtype: button_1
    id: "1_l"
  - platform: device
    domain: hue
    device_id: !input device
    type: short_release
    subtype: button_2
    id: "2_s"
  - platform: device
    domain: hue
    device_id: !input device
    type: initial_press
    subtype: button_2
    id: "2_h"
  - platform: device
    domain: hue
    device_id: !input device
    type: short_release
    subtype: button_3
    id: "3_s"
  - platform: device
    domain: hue
    device_id: !input device
    type: initial_press
    subtype: button_3
    id: "3_h"
  - platform: device
    domain: hue
    device_id: !input device
    type: short_release
    subtype: button_4
    id: "4_s"
  - platform: device
    domain: hue
    device_id: !input device
    type: long_release
    subtype: button_4
    id: "4_l"

action:
  - choose:
      # BUTTON 1: Power Toggle (Hardcoded)
      - conditions: "{{ trigger.id == '1_s' }}"
        sequence:
          - service: light.toggle
            target: !input target_light
      - conditions: "{{ trigger.id == '1_l' }}"
        sequence: !input button_1_long

      # BUTTON 2: Smooth Brighten
      - conditions: "{{ trigger.id == '2_s' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: 10
      - conditions: "{{ trigger.id == '2_h' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay: 0.5

      # BUTTON 3: Smooth Dim
      - conditions: "{{ trigger.id == '3_s' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: -10
      - conditions: "{{ trigger.id == '3_h' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay: 0.5

      # BUTTON 4: Hue Logo (Custom Actions)
      - conditions: "{{ trigger.id == '4_s' }}"
        sequence: !input button_4_short
      - conditions: "{{ trigger.id == '4_l' }}"
        sequence: !input button_4_long
