blueprint:
  name: "Hue Dimmer V2 (RWL022)"
  description: >
    Wähle nur die Entität von Button 1 aus. Die restlichen Buttons werden automatisch erkannt.
  domain: automation
  input:
    button_one_entity:
      name: Button 1 Entität
      description: Wähle die Entität '...button_1' deines Schalters aus.
      selector:
        entity:
          filter:
            - domain: event
              device_class: button
    light_target:
      name: Licht / Gruppe
      selector:
        target:
          entity:
            domain: light
    button_1_long:
      name: Button 1 (Ein) - Langer Druck
      default: []
      selector: { action: {} }
    button_4_short:
      name: Button 4 (Hue Logo) - Kurzer Druck
      default: []
      selector: { action: {} }
    button_4_long:
      name: Button 4 (Hue Logo) - Langer Druck
      default: []
      selector: { action: {} }

mode: restart
max_exceeded: silent

trigger:
  # Wir triggern auf alle 4 Button-Entitäten, indem wir den Namen dynamisch bestimmen
  - platform: state
    entity_id: !input button_one_entity
  - platform: state
    entity_id: 
      - "{{ (!input button_one_entity).replace('_button_1', '_button_2') }}"
      - "{{ (!input button_one_entity).replace('_button_1', '_button_3') }}"
      - "{{ (!input button_one_entity).replace('_button_1', '_button_4') }}"

action:
  - variables:
      # Wir holen uns den Event-Typ (z.B. short_release) aus den Attributen
      event_type: "{{ trigger.to_state.attributes.event_type }}"
      # Wir bestimmen, welcher Button gedrückt wurde
      triggered_entity: "{{ trigger.entity_id }}"
      base_name: "{{ (!input button_one_entity).replace('_button_1', '') }}"

  - choose:
      # BUTTON 1
      - conditions: "{{ triggered_entity == base_name ~ '_button_1' }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence:
                  - service: light.toggle
                    target: !input light_target
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_1_long

      # BUTTON 2 (Heller)
      - conditions:
          - "{{ triggered_entity == base_name ~ '_button_2' }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: 5

      # BUTTON 3 (Dunkler)
      - conditions:
          - "{{ triggered_entity == base_name ~ '_button_3' }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: -5

      # BUTTON 4
      - conditions: "{{ triggered_entity == base_name ~ '_button_4' }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence: !input button_4_short
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_4_long
