blueprint:
  name: "Hue Dimmer Switch V2 (RWL022) - Fast, Smooth & Custom Control"
  description: >
    ### 🎮 Professionelle Steuerung für den Hue Dimmer Switch V2 (RWL022)
    
    **Funktionen:**
    * **Button 1 (Oben):** Kurz drücken für Licht an/aus (Toggle). Lange drücken für eine freie Aktion.
    * **Button 2 (Sonne oben):** Schnelles & weiches Hochdimmen (10% Schritte, 0.1s Übergang).
    * **Button 3 (Sonne unten):** Schnelles & weiches Runterdimmen (10% Schritte, 0.1s Übergang).
    * **Button 4 (Hue Logo):** Frei belegbar für kurzen und langen Tastendruck (z.B. Szenen).
    
    **Sicherheit:** Nutzt manuelle Button-Wahl, um Systemlast zu vermeiden und maximale Stabilität zu garantieren.
  domain: automation
  input:
    button_1:
      name: Button 1 (Ein/Aus - Oben)
      description: Die Event-Entität für Button 1 (z.B. event.xxx_button_1)
      selector: { entity: { filter: { domain: event } } }
    button_2:
      name: Button 2 (Heller)
      description: Die Event-Entität für Button 2 (z.B. event.xxx_button_2)
      selector: { entity: { filter: { domain: event } } }
    button_3:
      name: Button 3 (Dunkler)
      description: Die Event-Entität für Button 3 (z.B. event.xxx_button_3)
      selector: { entity: { filter: { domain: event } } }
    button_4:
      name: Button 4 (Hue Logo - Unten)
      description: Die Event-Entität für Button 4 (z.B. event.xxx_button_4)
      selector: { entity: { filter: { domain: event } } }
    
    light_target:
      name: Licht / Gruppe
      description: Wähle die Lichter aus, die gesteuert werden sollen.
      selector: { target: { entity: { domain: light } } }

    button_1_long:
      name: Button 1 - Langer Druck (Aktion)
      description: Aktion, wenn Button 1 gehalten wird.
      default: []
      selector: { action: {} }
    button_4_short:
      name: Button 4 - Kurzer Druck (Aktion)
      description: Aktion, wenn das Hue Logo kurz gedrückt wird.
      default: []
      selector: { action: {} }
    button_4_long:
      name: Button 4 - Langer Druck (Aktion)
      description: Aktion, wenn das Hue Logo gehalten wird.
      default: []
      selector: { action: {} }

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input button_1
    id: "1"
  - platform: state
    entity_id: !input button_2
    id: "2"
  - platform: state
    entity_id: !input button_3
    id: "3"
  - platform: state
    entity_id: !input button_4
    id: "4"

action:
  - variables:
      event_type: "{{ trigger.to_state.attributes.event_type }}"

  - choose:
      # BUTTON 1
      - conditions: "{{ trigger.id == '1' }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence:
                  - service: light.toggle
                    target: !input light_target
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_1_long

      # BUTTON 2 (Heller)
      - conditions:
          - "{{ trigger.id == '2' }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: 2.5
              transition: 0.1

      # BUTTON 3 (Dunkler)
      - conditions:
          - "{{ trigger.id == '3' }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: -2.5
              transition: 0.1

      # BUTTON 4
      - conditions: "{{ trigger.id == '4' }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence: !input button_4_short
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_4_long
