blueprint:
  name: Native Hue - RWL022 Smooth Dimmer (Final Fix)
  description: |
    Smooth dimming for Philips Hue Dimmer RWL022 (v2) via Native Hue.
    Button 2/3: Hold to dim smoothly, Tap to step.
    Button 1/4: Custom actions.
  domain: automation
  input:
    device:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
          entity:
            domain: sensor
            device_class: battery
    target_light:
      name: Light(s) to control
      selector:
        target:
          entity:
            domain: light

    button_1_short:
      name: "Button 1 (Top) - Short"
      default: []
      selector:
        action:
    button_4_short:
      name: "Button 4 (Bottom) - Short"
      default: []
      selector:
        action:

mode: restart # Stoppt das Dimmen sofort beim Loslassen
max_exceeded: silent

trigger:
  # Button 1: Power
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 1
    id: "1_short"
  
  # Button 2: Brighten
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 2
    id: "2_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    subtype: 2
    id: "2_hold"

  # Button 3: Dim
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 3
    id: "3_short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    subtype: 3
    id: "3_hold"

  # Button 4: Hue
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    subtype: 4
    id: "4_short"

action:
  - choose:
      # Button 1 Action
      - conditions: "{{ trigger.id == '1_short' }}"
        sequence: !input button_1_short

      # Button 2: Brighten (Tap = 10%, Hold = Smooth Loop)
      - conditions: "{{ trigger.id == '2_short' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: 10
      - conditions: "{{ trigger.id == '2_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay: 0.5

      # Button 3: Dim (Tap = -10%, Hold = Smooth Loop)
      - conditions: "{{ trigger.id == '3_short' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: -10
      - conditions: "{{ trigger.id == '3_hold' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay: 0.5

      # Button 4 Action
      - conditions: "{{ trigger.id == '4_short' }}"
        sequence: !input button_4_short
