blueprint:
  name: "Hue Dimmer V2 - Ultra Smooth & Fast Control"
  description: >
    ### 🎮 Pro-Steuerung für den Hue Dimmer Switch V2
    Optimiert für absolut flüssiges Dimmen ohne Ruckeln.
    
    **Tipp gegen Ruckeln:** Wenn es stockt, erhöhe die 'Übergangszeit' leicht (z.B. auf 0.3s oder 0.4s).
  domain: automation
  input:
    button_1:
      name: Button 1 (Ein/Aus)
      selector: { entity: { filter: { domain: event } } }
    button_2:
      name: Button 2 (Heller)
      selector: { entity: { filter: { domain: event } } }
    button_3:
      name: Button 3 (Dunkler)
      selector: { entity: { filter: { domain: event } } }
    button_4:
      name: Button 4 (Hue Logo)
      selector: { entity: { filter: { domain: event } } }
    light_target:
      name: Licht / Gruppe
      selector: { target: { entity: { domain: light } } }
    
    # NEU: Tuning-Parameter für das Ruckeln
    dim_step:
      name: Dimm-Schrittweite
      description: Wie viel % sich die Helligkeit pro Befehl ändert.
      default: 10
      selector: { number: { min: 1, max: 25, unit_of_measurement: "%" } }
    dim_transition:
      name: Übergangszeit (Smoothness)
      description: "Zeit für den Übergang. Höhere Werte = smoother, aber 'gummiger'. Niedrigere Werte = direkter, aber ruckeliger."
      default: 0.3
      selector: { number: { min: 0, max: 1, step: 0.1, unit_of_measurement: "s" } }

    button_1_long:
      name: Button 1 - Langer Druck
      default: []
      selector: { action: {} }
    button_4_short:
      name: Button 4 - Kurzer Druck
      default: []
      selector: { action: {} }
    button_4_long:
      name: Button 4 - Langer Druck
      default: []
      selector: { action: {} }

mode: restart # Wichtig: Unterbricht laufende Animationen für sofortige Reaktion
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input button_1
    id: "1"
  - platform: state
    entity_id: !input button_2
    id: "2"
  - platform: state
    entity_id: !input button_3
    id: "3"
  - platform: state
    entity_id: !input button_4
    id: "4"

action:
  - variables:
      event_type: "{{ trigger.to_state.attributes.event_type }}"
      step: !input dim_step
      trans: !input dim_transition

  - choose:
      # BUTTON 1
      - conditions: "{{ trigger.id == '1' }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence:
                  - service: light.toggle
                    target: !input light_target
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_1_long

      # BUTTON 2 (Heller)
      - conditions:
          - "{{ trigger.id == '2' }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: "{{ step }}"
              transition: "{{ trans }}"

      # BUTTON 3 (Dunkler)
      - conditions:
          - "{{ trigger.id == '3' }}"
          - "{{ event_type in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_step_pct: "{{ step * -1 }}"
              transition: "{{ trans }}"

      # BUTTON 4
      - conditions: "{{ trigger.id == '4' }}"
        sequence:
          - choose:
              - conditions: "{{ event_type == 'short_release' }}"
                sequence: !input button_4_short
              - conditions: "{{ event_type == 'long_press' }}"
                sequence: !input button_4_long
