blueprint:
  name: "Hue Dimmer V2 - Clean Control"
  description: "Einfache Steuerung: Button 1 (Toggle), Button 2/3 (Dimmen), Button 4 (Frei)."
  domain: automation
  input:
    # Die 4 physischen Tasten als Event-Entitäten
    button_1:
      name: Taste 1 (Oben - Ein/Aus)
      selector: { entity: { filter: { domain: event } } }
    button_2:
      name: Taste 2 (Heller)
      selector: { entity: { filter: { domain: event } } }
    button_3:
      name: Taste 3 (Dunkler)
      selector: { entity: { filter: { domain: event } } }
    button_4:
      name: Taste 4 (Unten - Hue Logo)
      selector: { entity: { filter: { domain: event } } }
    
    # Das Ziel-Licht
    light_target:
      name: Licht / Gruppe
      selector: { target: { entity: { domain: light } } }

    # Die freien Belegungen
    button_1_long:
      name: Taste 1 - Langer Druck (Aktion)
      default: []
      selector: { action: {} }
    button_4_short:
      name: Taste 4 - Kurzer Druck (Aktion)
      default: []
      selector: { action: {} }
    button_4_long:
      name: Taste 4 - Langer Druck (Aktion)
      default: []
      selector: { action: {} }

mode: restart # Stoppt vorherige Dimm-Vorgänge sofort bei neuem Tastendruck
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input button_1
    id: "1"
  - platform: state
    entity_id: !input button_2
    id: "2"
  - platform: state
    entity_id: !input button_3
    id: "3"
  - platform: state
    entity_id: !input button_4
    id: "4"

action:
  - variables:
      # Wir lesen aus, WAS mit der Taste gemacht wurde (short_release, repeat, etc.)
      event: "{{ trigger.to_state.attributes.event_type }}"

  - choose:
      # Taste 1: Kurz = Toggle / Lang = Custom
      - conditions: "{{ trigger.id == '1' }}"
        sequence:
          - choose:
              - conditions: "{{ event == 'short_release' }}"
                sequence:
                  - service: light.toggle
                    target: !input light_target
              - conditions: "{{ event == 'long_press' }}"
                sequence: !input button_1_long

      # Taste 2: Heller (5% Schritte)
      - conditions:
          - "{{ trigger.id == '2' }}"
          - "{{ event in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data: { brightness_step_pct: 5 }

      # Taste 3: Dunkler (5% Schritte)
      - conditions:
          - "{{ trigger.id == '3' }}"
          - "{{ event in ['initial_press', 'repeat'] }}"
        sequence:
          - service: light.turn_on
            target: !input light_target
            data: { brightness_step_pct: -5 }

      # Taste 4: Kurz = Custom / Lang = Custom
      - conditions: "{{ trigger.id == '4' }}"
        sequence:
          - choose:
              - conditions: "{{ event == 'short_release' }}"
                sequence: !input button_4_short
              - conditions: "{{ event == 'long_press' }}"
                sequence: !input button_4_long
