blueprint:
  name: Hue RWL022 (V2) Single Device Selector
  description: Wähle nur den Schalter aus. Erwartet die offizielle Philips Hue Integration.
  domain: automation
  input:
    device:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
          # This entity check removes all lamps (Bedroom 1-5) from the list
          entity:
            domain: sensor
            device_class: battery

    target_light:
      name: Ziel-Lampen
      selector:
        target:
          entity:
            domain: light
    button_1_long:
      name: Taste 1 (Ein/Aus) - Langer Druck
      default: []
      selector:
        action:
    button_4_short:
      name: Taste 4 (Hue Logo) - Kurzer Druck
      default: []
      selector:
        action:
    button_4_long:
      name: Taste 4 (Hue Logo) - Langer Druck
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  # Button 1 (An/Aus)
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: short_release
    subtype: button_1
    id: btn1_short
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: long_release
    subtype: button_1
    id: btn1_long

  # Button 2 (Heller)
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: short_release
    subtype: button_2
    id: btn2_short
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: initial_press
    subtype: button_2
    id: btn2_long

  # Button 3 (Dunkler)
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: short_release
    subtype: button_3
    id: btn3_short
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: initial_press
    subtype: button_3
    id: btn3_long

  # Button 4 (Hue Taste)
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: short_release
    subtype: button_4
    id: btn4_short
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: long_release
    subtype: button_4
    id: btn4_long

  # Stop-Trigger für das Dimmen (beim Loslassen von Button 2 oder 3)
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: long_release
    subtype: button_2
    id: stop_loop
  - platform: device
    domain: hue
    device_id: !input hue_device
    type: long_release
    subtype: button_3
    id: stop_loop

action:
  - choose:
      # Taste 1 Toggle
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn1_short' }}"
        sequence:
          - action: light.toggle
            target: !input target_light

      # Taste 1 Long Press (Benutzerdefiniert)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn1_long' }}"
        sequence: !input button_1_long

      # Taste 2 (Heller) - Kurz
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn2_short' }}"
        sequence:
          - action: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: 10

      # Taste 2 (Heller) - Lang (Dimmen-Schleife)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn2_long' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - action: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # Taste 3 (Dunkler) - Kurz
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn3_short' }}"
        sequence:
          - action: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: -10

      # Taste 3 (Dunkler) - Lang (Dimmen-Schleife)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn3_long' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - action: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay:
                    milliseconds: 500

      # Taste 4 Kurz (Benutzerdefiniert)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn4_short' }}"
        sequence: !input button_4_short

      # Taste 4 Lang (Benutzerdefiniert)
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'btn4_long' }}"
        sequence: !input button_4_long

      # Stoppt die Schleife durch mode: restart
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'stop_loop' }}"
        sequence: []
