blueprint:
  name: Native Hue - Philips Hue Dimmer Switch RWL022 ONLY
  description: |
    Control your home using the Philips Hue Dimmer Switch (v2 / RWL022) via the NATIVE Hue integration.
    
    This blueprint is strictly filtered to only show the RWL022 model and excludes all lamps or other devices.
    Supported actions: Short Press and Long Press (on release) for all 4 buttons.
  domain: automation
  input:
    remote:
      name: Hue Dimmer Switch (RWL022)
      description: Select your RWL022 Dimmer Switch.
      selector:
        device:
          integration: hue
          model: RWL022
          entity:
            domain: sensor
            device_class: battery

    # Button 1: Power (Top)
    button_1_short:
      name: "Button 1 (Power) - Short Press"
      default: []
      selector:
        action:
    button_1_long:
      name: "Button 1 (Power) - Long Press"
      default: []
      selector:
        action:

    # Button 2: Brighten
    button_2_short:
      name: "Button 2 (Brighten) - Short Press"
      default: []
      selector:
        action:
    button_2_long:
      name: "Button 2 (Brighten) - Long Press"
      default: []
      selector:
        action:

    # Button 3: Dim
    button_3_short:
      name: "Button 3 (Dim) - Short Press"
      default: []
      selector:
        action:
    button_3_long:
      name: "Button 3 (Dim) - Long Press"
      default: []
      selector:
        action:

    # Button 4: Hue Logo (Bottom)
    button_4_short:
      name: "Button 4 (Hue Logo) - Short Press"
      default: []
      selector:
        action:
    button_4_long:
      name: "Button 4 (Hue Logo) - Long Press"
      default: []
      selector:
        action:

mode: parallel
max_exceeded: silent

trigger:
  - platform: device
    domain: hue
    device_id: !input remote
    type: remote_button_short_release
    id: "short"
  - platform: device
    domain: hue
    device_id: !input remote
    type: remote_button_long_release
    id: "long"

action:
  - variables:
      # Native Hue integration uses subtypes 1, 2, 3, 4 for the buttons
      button_id: "{{ trigger.subtype }}"
      press_type: "{{ trigger.id }}"

  - choose:
      # Button 1: Power
      - conditions: "{{ button_id == 1 and press_type == 'short' }}"
        sequence: !input button_1_short
      - conditions: "{{ button_id == 1 and press_type == 'long' }}"
        sequence: !input button_1_long

      # Button 2: Brighten
      - conditions: "{{ button_id == 2 and press_type == 'short' }}"
        sequence: !input button_2_short
      - conditions: "{{ button_id == 2 and press_type == 'long' }}"
        sequence: !input button_2_long

      # Button 3: Dim
      - conditions: "{{ button_id == 3 and press_type == 'short' }}"
        sequence: !input button_3_short
      - conditions: "{{ button_id == 3 and press_type == 'long' }}"
        sequence: !input button_3_long

      # Button 4: Hue Logo
      - conditions: "{{ button_id == 4 and press_type == 'short' }}"
        sequence: !input button_4_short
      - conditions: "{{ button_id == 4 and press_type == 'long' }}"
        sequence: !input button_4_long
