blueprint:
  name: Hue RWL022 Toggle and Smooth Dimmer
  description: |
    A comprehensive controller for the Philips Hue Dimmer Switch (v2 / RWL022) 
    using the native Philips Hue integration.

    Features:
    - Button 1 (Top): Hardcoded to toggle 'Target Light(s)' on short press. Customizable long press.
    - Button 2 & 3 (Center): Tap to step brightness or hold for smooth continuous dimming.
    - Button 4 (Bottom): Fully customizable short and long press actions.
    - Optimized Selector: Only shows RWL022 devices and automatically hides lamps.

    Required Hardware: Philips Hue Dimmer Switch model RWL022 connected via the Hue Bridge.
  domain: automation
  input:
    device:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
              model: "Hue dimmer switch (RWL022)"
          entity:
            domain: sensor
            device_class: battery
    target_light:
      name: Target Light(s)
      description: The lights controlled by the Power Toggle (Button 1) and Dimming (Buttons 2 & 3).
      selector:
        target:
          entity:
            domain: light

    # Custom Action Slots
    button_1_long:
      name: Button 1 (Power) - Long Press Action
      default: []
      selector:
        action:
    button_4_short:
      name: Button 4 (Hue Logo) - Short Press Action
      default: []
      selector:
        action:
    button_4_long:
      name: Button 4 (Hue Logo) - Long Press Action
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  # Button 1
  - platform: device
    domain: hue
    device_id: !input device
    type: short_release
    subtype: button_1
    id: "1_s"
  - platform: device
    domain: hue
    device_id: !input device
    type: long_release
    subtype: button_1
    id: "1_l"

  # Button 2
  - platform: device
    domain: hue
    device_id: !input device
    type: short_release
    subtype: button_2
    id: "2_s"
  - platform: device
    domain: hue
    device_id: !input device
    type: initial_press
    subtype: button_2
    id: "2_h"

  # Button 3
  - platform: device
    domain: hue
    device_id: !input device
    type: short_release
    subtype: button_3
    id: "3_s"
  - platform: device
    domain: hue
    device_id: !input device
    type: initial_press
    subtype: button_3
    id: "3_h"

  # Button 4
  - platform: device
    domain: hue
    device_id: !input device
    type: short_release
    subtype: button_4
    id: "4_s"
  - platform: device
    domain: hue
    device_id: !input device
    type: long_release
    subtype: button_4
    id: "4_l"

action:
  - choose:
      # BUTTON 1: Power Toggle
      - conditions: "{{ trigger.id == '1_s' }}"
        sequence:
          - service: light.toggle
            target: !input target_light
      - conditions: "{{ trigger.id == '1_l' }}"
        sequence: !input button_1_long

      # BUTTON 2: Smooth Brighten
      - conditions: "{{ trigger.id == '2_s' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: 10
      - conditions: "{{ trigger.id == '2_h' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay: 0.5

      # BUTTON 3: Smooth Dim
      - conditions: "{{ trigger.id == '3_s' }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness_step_pct: -10
      - conditions: "{{ trigger.id == '3_h' }}"
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: "{{ true }}"
              sequence:
                - service: light.turn_on
                  target: !input target_light
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay: 0.5

      # BUTTON 4: Hue Logo
      - conditions: "{{ trigger.id == '4_s' }}"
        sequence: !input button_4_short
      - conditions: "{{ trigger.id == '4_l' }}"
        sequence: !input button_4_long
