blueprint:
  name: Native Hue - Philips Hue Dimmer Switch RWL022 (Final)
  description: |
    Control anything using a Philips Hue Dimmer Switch (RWL022) via the NATIVE Hue integration.
    This uses a strict multi-filter to show ONLY the RWL022 and exclude all lamps.
    
    Actions: Short Press and Long Press (on release) for all 4 buttons.
  domain: automation
  input:
    device: # Following your preferred naming
      name: Philips Hue Dimmer Switch
      selector:
        device:
          entity:
            domain: sensor
            device_class: battery

    # Button 1: Power (Top)
    button_1_short:
      name: "Button 1 (Power) - Short Press"
      default: []
      selector:
        action:
    button_1_long:
      name: "Button 1 (Power) - Long Press"
      default: []
      selector:
        action:

    # Button 2: Brighten
    button_2_short:
      name: "Button 2 (Brighten) - Short Press"
      default: []
      selector:
        action:
    button_2_long:
      name: "Button 2 (Brighten) - Long Press"
      default: []
      selector:
        action:

    # Button 3: Dim
    button_3_short:
      name: "Button 3 (Dim) - Short Press"
      default: []
      selector:
        action:
    button_3_long:
      name: "Button 3 (Dim) - Long Press"
      default: []
      selector:
        action:

    # Button 4: Hue Logo (Bottom)
    button_4_short:
      name: "Button 4 (Hue Logo) - Short Press"
      default: []
      selector:
        action:
    button_4_long:
      name: "Button 4 (Hue Logo) - Long Press"
      default: []
      selector:
        action:

mode: parallel
max_exceeded: silent

trigger:
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    id: "short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_long_release
    id: "long"

action:
  - variables:
      # Native Hue integration uses button subtypes 1, 2, 3, 4
      button_id: "{{ trigger.subtype }}"
      press_type: "{{ trigger.id }}"

  - choose:
      - conditions: "{{ button_id == 1 and press_type == 'short' }}"
        sequence: !input button_1_short
      - conditions: "{{ button_id == 1 and press_type == 'long' }}"
        sequence: !input button_1_long

      - conditions: "{{ button_id == 2 and press_type == 'short' }}"
        sequence: !input button_2_short
      - conditions: "{{ button_id == 2 and press_type == 'long' }}"
        sequence: !input button_2_long

      - conditions: "{{ button_id == 3 and press_type == 'short' }}"
        sequence: !input button_3_short
      - conditions: "{{ button_id == 3 and press_type == 'long' }}"
        sequence: !input button_3_long

      - conditions: "{{ button_id == 4 and press_type == 'short' }}"
        sequence: !input button_4_short
      - conditions: "{{ button_id == 4 and press_type == 'long' }}"
        sequence: !input button_4_long
