blueprint:
  name: Native Hue - RWL022 Smooth Dimming (Selection Fixed)
  description: |
    Control lights with a Philips Hue Dimmer Switch (RWL022) via NATIVE Hue integration.
    
    Features:
    - Smooth dimming: Hold buttons 2 or 3 to fade lights up/down.
    - Reliable selection: Uses battery filter to find the switch and hide lamps.
  domain: automation
  input:
    device:
      name: Philips Hue Dimmer Switch
      selector:
        device:
          filter:
            - integration: hue
          entity:
            domain: sensor
            device_class: battery
    target_light:
      name: Light(s) to control
      selector:
        target:
          entity:
            domain: light

    # Custom actions for Top and Bottom buttons
    button_1_short:
      name: "Button 1 (Power) - Short Press"
      default: []
      selector:
        action:
    button_1_long:
      name: "Button 1 (Power) - Long Press"
      default: []
      selector:
        action:
    button_4_short:
      name: "Button 4 (Hue Logo) - Short Press"
      default: []
      selector:
        action:
    button_4_long:
      name: "Button 4 (Hue Logo) - Long Press"
      default: []
      selector:
        action:

mode: restart # Important to stop previous dimming loops immediately
max_exceeded: silent

trigger:
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_short_release
    id: "short"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_long_release
    id: "long_release"
  - platform: device
    domain: hue
    device_id: !input device
    type: remote_button_initial_press
    id: "initial"

action:
  - variables:
      button_id: "{{ trigger.subtype }}"
      press_type: "{{ trigger.id }}"

  - choose:
      # BUTTON 1 (POWER)
      - conditions: "{{ button_id == 1 and press_type == 'short' }}"
        sequence: !input button_1_short
      - conditions: "{{ button_id == 1 and press_type == 'long_release' }}"
        sequence: !input button_1_long

      # BUTTON 2 (BRIGHTEN) - SMOOTH DIMMING
      - conditions: "{{ button_id == 2 }}"
        sequence:
          - if: "{{ press_type == 'short' }}"
            then:
              - service: light.turn_on
                target: !input target_light
                data:
                  brightness_step_pct: 10
          - if: "{{ press_type == 'initial' }}"
            then:
              - repeat:
                  while:
                    - condition: template
                      value_template: "{{ true }}" # Loop runs until stopped by 'mode: restart' on release
                  sequence:
                    - service: light.turn_on
                      target: !input target_light
                      data:
                        brightness_step_pct: 10
                        transition: 0.5
                    - delay: 0.5

      # BUTTON 3 (DIM) - SMOOTH DIMMING
      - conditions: "{{ button_id == 3 }}"
        sequence:
          - if: "{{ press_type == 'short' }}"
            then:
              - service: light.turn_on
                target: !input target_light
                data:
                  brightness_step_pct: -10
          - if: "{{ press_type == 'initial' }}"
            then:
              - repeat:
                  while:
                    - condition: template
                      value_template: "{{ true }}"
                  sequence:
                    - service: light.turn_on
                      target: !input target_light
                      data:
                        brightness_step_pct: -10
                        transition: 0.5
                    - delay: 0.5

      # BUTTON 4 (HUE LOGO)
      - conditions: "{{ button_id == 4 and press_type == 'short' }}"
        sequence: !input button_4_short
      - conditions: "{{ button_id == 4 and press_type == 'long_release' }}"
        sequence: !input button_4_long
